package jsx.indesign;

/*
 * Shape options for the intersection of three-way traps.
 */
typedef TrapEndTypes = {
  /*
   * Shapes the end of the trap to keep it away from the intersecting object.
   */
  var MITER_TRAP_ENDS:Float;
  /*
   * Reshapes the trap generated by the lightest neutral density object so that it wraps around the point where the three objects intersect.
   */
  var OVERLAP_TRAP_ENDS:Float;
};